// Terminal Red — pure simulation engine (fake ingest).
// No React, no wall clock, no I/O: callers supply the rng, so every
// step is deterministic and unit-testable.

export type Rng = () => number
export type NodeStatus = "OK" | "CRITICAL" | "SEVERED" | "DRAINED"
export type NodeRole = "EDGE" | "API" | "DB" | "CACHE" | "QUEUE" | "WORKER"
export type Command = "KILL" | "RESTART" | "DRAIN"
export type LogLevel = "INFO" | "WARN" | "ERROR"

export interface SimNode {
  id: string
  role: NodeRole
  cpu: number
  mem: number
  disk: number
  reqRate: number
  status: NodeStatus
}

export type StepEvent =
  | { kind: "TRAFFIC"; nodeId: string; level: LogLevel; message: string }
  | { kind: "INCIDENT_OPEN"; incidentId: string }
  | { kind: "CRITICAL"; nodeId: string; incidentId: string }
  | { kind: "RECOVERY"; nodeId: string }
  | { kind: "INCIDENT_CLOSE"; incidentId: string }

export interface SimState {
  tick: number
  incidentSeq: number
  incidentId: string | null
  nodes: SimNode[]
  /** Events generated by the most recent stepSim/execCommand call. */
  lastEvents: StepEvent[]
}

const ROLES: NodeRole[] = ["EDGE", "EDGE", "API", "API", "DB", "CACHE", "QUEUE", "WORKER"]

/** Static node identity — safe to render before the sim boots. */
export const NODE_DEFS: { id: string; role: NodeRole }[] = ROLES.map((role, i) => ({
  id: `NODE-${String(i + 1).padStart(2, "0")}`,
  role,
}))

/** Per-node, per-tick probability a healthy node flips CRITICAL. */
const CRIT_P = 0.008

const TRAFFIC = [
  "GET /V1/METRICS 200",
  "HEARTBEAT OK",
  "CACHE HIT RATIO 0.97",
  "QUEUE DEPTH NOMINAL",
  "REPLICA LAG 12MS",
  "TLS HANDSHAKE OK",
  "GC PAUSE 0MS",
  "POOL CHECKOUT 2MS",
  "SHARD REBALANCE IDLE",
  "WAL FLUSH OK",
  "DNS RESOLVE 4MS",
  "UPSTREAM 200 OK",
]

const CRIT_TRAFFIC = [
  "5XX RATE SPIKE",
  "HEALTHCHECK TIMEOUT",
  "CONNECTION POOL EXHAUSTED",
  "THREAD POOL SATURATED",
  "OOM KILLER ARMED",
  "RETRY STORM DETECTED",
]

const clamp = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, v))

/** Random walk: instant value jumps, clamped. */
const walk = (v: number, spread: number, lo: number, hi: number, rng: Rng) =>
  clamp(Math.round(v + (rng() * 2 - 1) * spread), lo, hi)

const pick = <T,>(arr: T[], rng: Rng): T => arr[Math.floor(rng() * arr.length)]

function freshMetrics(rng: Rng) {
  return {
    cpu: 8 + Math.floor(rng() * 25),
    mem: 20 + Math.floor(rng() * 35),
    disk: 25 + Math.floor(rng() * 45),
    reqRate: 400 + Math.floor(rng() * 4200),
  }
}

/** Deterministic PRNG for tests. */
export function mulberry32(seed: number): Rng {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

export function initSim(rng: Rng): SimState {
  return {
    tick: 0,
    incidentSeq: 0,
    incidentId: null,
    lastEvents: [],
    nodes: NODE_DEFS.map((def) => ({ ...def, ...freshMetrics(rng), status: "OK" as NodeStatus })),
  }
}

/** Prepend into a ring buffer: newest first, hard cap. */
export function ringPush<T>(buf: T[], item: T, cap: number): T[] {
  const next = [item, ...buf]
  return next.length > cap ? next.slice(0, cap) : next
}

export function stepSim(state: SimState, rng: Rng): SimState {
  const events: StepEvent[] = []
  let incidentId = state.incidentId
  let incidentSeq = state.incidentSeq

  const nodes: SimNode[] = state.nodes.map((n) => {
    switch (n.status) {
      case "SEVERED":
        // Dead is dead. Only an operator RESTART resurrects a node.
        return n
      case "CRITICAL":
        return {
          ...n,
          cpu: 95 + Math.floor(rng() * 5),
          mem: walk(n.mem, 6, 70, 99, rng),
          disk: walk(n.disk, 2, 10, 99, rng),
          reqRate: walk(n.reqRate, 900, 0, 9999, rng),
        }
      case "DRAINED":
        return {
          ...n,
          cpu: walk(n.cpu, 4, 1, 24, rng),
          mem: walk(n.mem, 3, 5, 70, rng),
          disk: walk(n.disk, 1, 10, 99, rng),
          reqRate: 0,
        }
      case "OK": {
        if (rng() < CRIT_P) {
          if (!incidentId) {
            incidentSeq += 1
            incidentId = `INC-${String(incidentSeq).padStart(3, "0")}`
            events.push({ kind: "INCIDENT_OPEN", incidentId })
          }
          events.push({ kind: "CRITICAL", nodeId: n.id, incidentId })
          return {
            ...n,
            status: "CRITICAL" as NodeStatus,
            cpu: 95 + Math.floor(rng() * 5),
            mem: clamp(n.mem + 20 + Math.floor(rng() * 15), 0, 99),
          }
        }
        return {
          ...n,
          cpu: walk(n.cpu, 9, 1, 93, rng),
          mem: walk(n.mem, 6, 5, 93, rng),
          disk: walk(n.disk, 2, 10, 93, rng),
          reqRate: walk(n.reqRate, 500, 50, 9999, rng),
        }
      }
    }
  })

  // Fake ingest traffic: 1-2 log lines per tick from live nodes.
  const live = nodes.filter((n) => n.status !== "SEVERED")
  const lines = 1 + (rng() < 0.4 ? 1 : 0)
  for (let i = 0; i < lines && live.length > 0; i++) {
    const n = pick(live, rng)
    if (n.status === "CRITICAL" && rng() < 0.6) {
      events.push({ kind: "TRAFFIC", nodeId: n.id, level: "ERROR", message: pick(CRIT_TRAFFIC, rng) })
    } else {
      events.push({
        kind: "TRAFFIC",
        nodeId: n.id,
        level: rng() < 0.15 ? "WARN" : "INFO",
        message: pick(TRAFFIC, rng),
      })
    }
  }

  return { ...state, tick: state.tick + 1, incidentId, incidentSeq, nodes, lastEvents: events }
}

/** Which operator commands are valid to offer for a node in this status. */
export function availableCommands(status: NodeStatus): Command[] {
  if (status === "SEVERED") return ["RESTART"]
  if (status === "DRAINED") return ["KILL", "RESTART"]
  return ["KILL", "RESTART", "DRAIN"]
}

/** One-click trigger execution: immediate, no confirmation. */
export function execCommand(state: SimState, nodeId: string, cmd: Command, rng: Rng): SimState {
  const events: StepEvent[] = []
  let incidentId = state.incidentId

  const nodes: SimNode[] = state.nodes.map((n) => {
    if (n.id !== nodeId) return n
    if (cmd === "KILL") return { ...n, status: "SEVERED" as NodeStatus, reqRate: 0 }
    if (cmd === "DRAIN") {
      if (n.status === "SEVERED") return n
      return { ...n, status: "DRAINED" as NodeStatus, reqRate: 0 }
    }
    // RESTART: fresh baseline, clears CRITICAL, resurrects SEVERED/DRAINED.
    if (n.status === "CRITICAL") events.push({ kind: "RECOVERY", nodeId: n.id })
    return { ...n, ...freshMetrics(rng), status: "OK" as NodeStatus }
  })

  if (incidentId && !nodes.some((n) => n.status === "CRITICAL")) {
    events.push({ kind: "INCIDENT_CLOSE", incidentId })
    incidentId = null
  }

  return { ...state, nodes, incidentId, lastEvents: events }
}
